"use strict";
var common = {};

common.GOOGLE_PLUS_PEOPLE_URL = "https://www.googleapis.com/plus/v1/people/";
common.FEATURED_URL = "/featured";
common.MESSAGES_URL = "/messages";
common.SEARCH_URL = "/search";
common.USER_URL = "/user";
common.USER_CHANNELS_URL = "/user/channels";
common.USER_CONTACTS_URL = "/user/contacts";
common.USER_FOLLOWER_COUNT_URL = "/user/following";
common.USER_GROUPS_URL = "/user/groups";
common.USER_SHARED_URL = "/user/shared";
common.USER_VERSION_URL = "/user/version";
common.ROOT_URL = "/";
common.USERS_URL = "/users";
common.WEBUSERS_URL = "/webusers";
common.GOOGLE_PERSON_URL = "/google/person";
common.USERS = "users";
common.USER = "user";
common.USERID = "userId";
common.CHANNELID = "channelId";
common.CONTACTID = "contactId";
common.GROUPID = "groupId";
common.GROUP = "group";
common.GROUPS = "groups";
common.VERSION = "version";
common.SHARED = "shared";
common.MESSAGES = "messages";
common.FEATURED = "featured";
common.VALUE = "value";
common.NAME = "name";
common.AUTH = "auth";
common.UNDEFINED = 'undefined';
common.ERROR = "error";
common.END = "end";
common.DATA = "data";
common.PARAM_KEY = "?key=";

module.exports = common;
